djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path("/", include('nova.urls')),
    path("admin/", admin.site.urls),
    # The web page start from the properties/
    path('properties/', include('nova.urls', namespace="properties")),
    path('users/', include('users.urls', namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

nova/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "nova"
urlpatterns = [
    # properties views
    # Home page for logged-in user -> dashboard, not logged in user -> ad page
    path('', views.home_page, name="home-page"),
    path('about', views.about, name="about"),
    # Item list page
    path('properties-list', views.properties_list, name="properties-list"),


    # Register (not yet implement), only has interface

    path('search-result', views.search_result, name="search-result"),

    # CRUD properties
    path('post-property-page', views.post_property_page, name="post-property-page"),
    path('<int:property_id>/delete', views.delete_property, name='delete-property'),
    path('<int:property_id>/edit', views.edit_property_page, name="edit-property-page"),
    path('<int:property_id>', views.property_detail, name="property-detail"),
    # Comment CRUD
    path('comments/post', views.post_comment, name="post-comment"),
    path('<int:property_id>/comments/<int:comment_id>/delete', views.delete_comment, name="delete-comment"),
    # path('comments/delete', views.delete_comment, name='delete-comment'),
    path('<int:property_id>/comments/<int:comment_id>/edit', views.edit_comment, name="edit-comment")
    # path('<int:property_id>/comments', views.comments, name="comments"),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
app_name = "users"
urlpatterns = [
    # properties views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('profile/<str:username>/edit', views.edit_profile, name='edit-profile'),
    # Log in, Log out
    path('log-in', views.log_in_page, name="log-in-page"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),


]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nova/views.py
from django.contrib.auth.models import User
from django.db.models import Avg
from django.db.models.functions import Coalesce
from django.db.models import Avg, Value, FloatField
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect

from actions.models import Action
from .models import regular_user, admin_user, Property, Comments
from datetime import datetime
from django.contrib import messages
from django.utils.timesince import timesince


# Home page if log in: user dashboard, if not: ad welcome page
def home_page(request):
    if not request.session.get('username', False):
        return render(request, "nova/property/home.html")
    else:
        properties = Property.objects.all()
        user = User.objects.get(username=request.session.get('username'))
        own_actions = Action.objects.filter(user=user)

        user_properties = Property.objects.filter(user=user)

        related_actions = Action.objects.filter(target_id=user.id, verb="changed the role of")

        for property in user_properties:
            actions_for_property = Action.objects.filter(target_id=property.id)
            related_actions = related_actions | actions_for_property

        combined_actions = own_actions | related_actions
        return_actions = combined_actions.order_by('-created')[:15]


        return render(request, "nova/property/home-logged-in.html", {"properties": properties, "actions": return_actions})


def properties_list(request):
    sort_by = request.GET.get('sort', 'availability')  # default sort is by 'date_posted'

    # Use Coalesce to set the default average rating to 0 (If no ratings)
    properties = Property.objects.annotate(
        average_rating=Coalesce(Avg('comments__rating'), Value(0), output_field=FloatField())
    )

    if sort_by == 'house_name':
        # properties = Property.objects.all().order_by('house_name')
        properties = properties.order_by('house_name')
    elif sort_by == 'rent_cost':
        # properties = Property.objects.all().order_by('rent_cost')
        properties = properties.order_by('rent_cost')
    else:
        # properties = Property.objects.all().order_by('-availability')  # '-' indicates descending order
        properties = properties.order_by('-availability')  # '-' indicates descending order
    return render(request, "nova/property/list.html", {"properties": properties})


def property_detail(request, property_id):
    properties = Property.objects.annotate(
        average_rating=Coalesce(Avg('comments__rating'), Value(0), output_field=FloatField())
    )
    property = get_object_or_404(Property, id=property_id)
    comments = property.comments.all()
    comments = comments.order_by('-date_posted')
    # Calculate the average rating if there are reviews
    average_rating = comments.aggregate(Avg('rating'))['rating__avg']
    if average_rating is not None:
        average_rating = round(average_rating, 1)

    for property in properties:
        if property.id == property_id:
            # comments = Comments.objects.get(property)
            break

    return render(request,
                  "nova/property/detail.html",
                  {"property": property, "comments": comments, "average_rating": average_rating})


# Log in for regular user or admin user, determine which kind of the user is logged in


# Post a property (only for who is logged in)
def post_property_page(request):
    if not request.session.get('username', False):
        return redirect('users:log-in-page')
    if request.method == 'POST':
        # process the form
        # id
        house_name = request.POST.get('add-house-name')
        address = request.POST.get('add-address')
        availability = request.POST.get('add-availability')
        bathrooms_count = request.POST.get('add-bathrooms-count')
        bedrooms_count = request.POST.get('add-bedrooms-count')
        city = request.POST.get('add-city')
        date_posted = datetime.now()
        description = request.POST.get('add-description')
        finding_rm = False
        floor = request.POST.get('add-floor')
        initial_fee = request.POST.get('add-initial-fee')
        is_verified = False
        poster = request.POST.get('add-poster')
        # rating = 0.0
        rent_cost = request.POST.get('add-rent-cost')
        size = request.POST.get('add-size')
        unit = request.POST.get('add-unit')
        wished = "admin"
        zip_code = request.POST.get('add-zip-code')
        photo = request.FILES.get('add-photo')
        print(photo)
        np = Property(

            house_name=house_name,
            address=address,
            availability=availability,
            bathrooms_count=bathrooms_count,
            bedrooms_count=bedrooms_count,
            city=city,
            date_posted=date_posted,
            description=description,
            finding_rm=finding_rm,
            floor=floor,
            initial_fee=initial_fee,
            is_verified=is_verified,
            poster=poster,
            # rating=rating,
            rent_cost=rent_cost,
            size=size,
            unit=unit,
            # url=url,
            # wished=wished,
            zip_code=zip_code,
            photo=photo,
            user=User.objects.get(username=request.session.get("username"))

        )
        # Save to database
        np.save()

        action = Action(
            user=User.objects.get(username=request.session.get("username")),
            verb="posted a new house",
            target=np
        )
        action.save()

        # Message for indicating the status
        messages.add_message(request, messages.SUCCESS, "You successfully posted a new property: %s" % np.house_name)
        print(house_name, "has been posted")

        return redirect("nova:property-detail", np.id)
    else:
        return render(request, "nova/property/post.html")


# def user_home(request):
#     return render(request, "nova/property/home-logged-in.html", {"properties": properties})


def search_result(request):
    return render(request, "nova/property/search-result.html")


# Delete property URL is only accessible for admin user, regular user can't access only be redirected to the list
# page, and logged-in user will be navigated to the login page
def delete_property(request, property_id):
    property_to_delete = Property.objects.get(id=property_id)
    property_title = property_to_delete.house_name
    print(request.session.get("username"))
    print(property_to_delete.user.username)
    if not request.session.get('username', False):
        print("Please log in")
        return redirect('users:log-in-page')
    elif not request.session['role'] == 'admin' and request.session.get("username") != property_to_delete.user.username:
        print("You don't have permission, not admin")
        return redirect('nova:properties-list')
    elif request.session.get("username") != property_to_delete.user.username:
        print("You don't have permission to delete others' posts")
    else:
        action = Action(
            user=User.objects.get(username=request.session.get("username")),
            verb="deleted the house",
            target=property_to_delete,
            deleted_house_name=property_to_delete.house_name
        )
        action.save()

        # Delete the property
        property_to_delete.delete()

        print("Property id", property_id, "has been deleted")
        messages.add_message(request, messages.WARNING, "You deleted a property: %s" % property_title)

        # TODO:Delete operation
        return redirect('nova:properties-list')


def about(request):
    return render(request, "nova/about.html")


# Only logged in user can edit the property, clicking the corresponded property in the home page will leads to the edit page
def edit_property_page(request, property_id):
    if not request.session.get('username', False):
        return redirect('users:log-in-page')
    if request.method == 'POST':
        properties = Property.objects.all()
        for property in properties:
            if property.id == property_id:
                break

        if not request.session.get('username', False):
            return redirect('users:log-in-page')
        if request.method == 'POST':
            # process the form
            # id
            house_name = request.POST.get('edit-house-name')
            if property.house_name != house_name:
                action = Action(
                    user=User.objects.get(username=request.session.get("username")),
                    verb="edited the house title",
                    target=property
                )
                action.save()
            property.house_name = house_name
            address = request.POST.get('edit-address')
            property.address = address
            availability = request.POST.get('edit-availability')
            property.availability = availability
            bathrooms_count = request.POST.get('edit-bathrooms-count')
            property.bathrooms_count = bathrooms_count
            bedrooms_count = request.POST.get('edit-bedrooms-count')
            property.bedrooms_count = bedrooms_count
            city = request.POST.get('edit-city')
            property.city = city
            # date_posted = datetime.now()
            # property.date_posted = datetime.now()
            description = request.POST.get('edit-description')
            if property.description != description:
                action = Action(
                    user=User.objects.get(username=request.session.get("username")),
                    verb="edited the house description",
                    target=property
                )
                action.save()
            property.description = description
            # finding_rm = False

templates/nova/property/detail.html
{% extends "nova/base.html" %}
{% block page-title %} Detail {% endblock %}
{% load static %}

{% load humanize %}
{% block content %}
    <link rel="stylesheet" type="text/css" href={% static "css/detail.css" %}>
    {#    Property Name: {{ property.house_name}}#}

    {#    <h3>Delete property</h3>#}
    {#    {% if request.session.role == 'admin' %}#}
    {#        <form class="delete-form" method="POST" actions="{% url "nova:delete-property" property.id %}">#}
    {#            {% csrf_token %}#}
    {#            <input type="submit" class="delete-btn"#}
    {#                   onclick="return confirm('Are you sure you want to delete this property?');"#}
    {#                   value="Delete">#}
    {#        </form>#}
    {#    {% endif %}#}


    <!--    Grid blocks for images 3 X 2-->
    <div id="house-images-section">
        <img id="main-image" src="{{ property.photo.url }}"
             alt="building">

        <!--        The pictures of the houses are from a website for free, public accessible photos https://unsplash.com/s/photos/house-->

        {#        <img class="detail-image" src="img/houses/house-detail-1.jpg" alt="wonderful-land-building">#}
        {#        <img class="detail-image" src="img/houses/house-detail-2.jpg" alt="wonderful-land-building">#}
        {#        <img class="detail-image" src="img/houses/house-detail-3.jpg" alt="wonderful-land-building">#}
        {#        <img class="detail-image" src="img/houses/house-detail-4.jpg" alt="wonderful-land-building">#}
        {#        <img class="detail-image" src="img/houses/house-detail-5.jpg" alt="wonderful-land-building">#}

    </div>

    <!--    Add to wish list-->
    {#    {% if request.session.username %}#}
    {#        <h4>Wish list <img class="wish-icon" src={% static "img/heart-plus.svg" %} alt="heart"></h4>#}
    {#    {% endif %}#}



    <!--    House detail sections contains more information-->
    <div id="house-detail-section">
{#        <img class="star" src={% static "img/star-solid.svg" %} alt="star">#}
{#        {% if property.average_rating %}#}
{#            {{ property.average_rating|floatformat:1 }}#}
{#            <hr>#}
{#        {% else %}#}
{#            No ratings yet#}
{#            <hr>#}
{#        {% endif %}#}


        <h4 class="verify"></h4>
        {% if property.is_verified %}
            <img class="badge" src={% static "img/badge_check_icon.svg" %} alt="badge"> Verified
        {% else %}
            Not Verified
        {% endif %}


        <h4 class="availability">
            {% if property.availability %}
                Open
            {% else %}
                Full
            {% endif %}
        </h4>

        <h1 id="house-name">{{ property.house_name }}</h1>

        <!--        The first part contain address and post information-->
        <div id="first-part">
            <p> {{ property.address }}</p>
            <h4>Posted By <a href="{% url 'users:profile' property.user.username %}">{{ property.user.username }}</a>
            </h4>

            <p>{{ property.date_posted|naturaltime }}</p>

        </div>
        <div id=" info">
            <!--        The second part contain costs, room-related information and others-->
            <div id="second-part">

                <div id="costs-related">
                    <div class="detail-items"><h4>Monthly Costs: </h4> <h4
                            class="info"> {{ property.rent_cost }}</h4>
                    </div>
                    <div class="detail-items"><h4>Initial Cost: </h4> <h4
                            class="info">{{ property.initial_fee }}</h4>
                    </div>
                    <div class="detail-items"><h4>First Month: </h4> <h4 class="info"> {{ property.rent_cost }}
                        + {{ property.initial_fee }}</h4></div>

                </div>


                <div class="detail-items"><h4>Beds: </h4> <h4 class="info"> {{ property.bedrooms_count }}</h4></div>
                <div class="detail-items"><h4>Baths: </h4> <h4 class="info"> {{ property.bathrooms_count }}</h4>
                </div>
                <div class="detail-items"><h4>Size </h4> <h4 class="info"> {{ property.size }} Sq Ft</h4></div>
                <div class="detail-items"><h4>Floor: </h4> <h4 class="info"> {{ property.floor }}</h4></div>


                {#                <div class="detail-items"><h4 id="finding-roommate-message">{{ property.finding_rm }} people are finding#}
                {#                    a#}
                {#                    roommate</h4></div>#}
                _________________________________
                {##}
                <br> <br>

                {#            <div id="stats">#}
                {#                <div class="detail-items"><h4>International Friendly? </h4> <h4 class="info"> 96% </h4> <h4#}
                {#                        class="info"></h4></div>#}
                {#                <div class="detail-items"><h4>Scam? </h4> <h4 class="info"> 0%</h4>  <h4 class="info"></h4>#}
                {#                </div>#}
                {#            </div>#}


                <h4>Description</h4>
                <div id="description-section">

                    <p id="description">
                        {{ property.description }}
                    </p>
                </div>


            </div>


            <!--The other part of the website is review and roommates-->
            <div id="review-section">
                <h3 id="review-section-title">Review and Roommates</h3>

                <!--            Filter options-->
                {#                <div id="filter">#}
                {#            <label for="filtered">-options"></label>#}
                {#                    <select name="filter-options" id="filter-options">#}
                {#                        <option value="filter-finding-roommates">Finding Roommates</option>#}
                {#                        <option value="filter-international-friendly">International Friendly</option>#}
                {#                    </select>#}
                {#                </div>#}

                {#                {% for comment in property.comments.all %}#}
                {##}
                {#                    <div class="review">#}
                {#                        <a href="#">{{ comment.poster }}</a>#}
                {#                        <img class="star" src={% static "img/star-solid.svg" %} alt="star"> {{ comment.rating }}#}
                {#                        <p>{{ comment.content }}</p>#}
                {#                        <h4>International Friendly? {% if comment.international_friendly %}Yes#}
                {#                        {% else %}NO#}
                {#                        {% endif %} </h4>#}
                {#                        <h4>Finding a roommate?  {% if comment.finding_rm %}Yes#}
                {#                        {% else %}NO#}
                {#                        {% endif %}</h4>#}
                {#                    </div>#}
                {##}
                {#                    <hr>#}
                {##}
                {##}
                {#                {% endfor %}#}

                <div id="commentsSection">

                    {% for comment in comments %}

                        <div class="review">
                            <div id="urlContainer" data-profile-url="{% url 'users:profile' 'USERNAME' %}">
                                <a href="{% url 'users:profile' comment.user.username %}">{{ comment.user.username }}</a>
                            </div>
                            <h5 id="dateString">Date posted: {{ comment.date_posted|naturaltime }}</h5>

                            <img class="star" src={% static "img/star-solid.svg" %} alt="star"> {{ comment.rating }}
                            <p>{{ comment.content }}</p>
                            <h4>International Friendly? {% if comment.international_friendly %}Yes
                            {% else %}NO
                            {% endif %} </h4>
                            <h4>Finding a roommate?  {% if comment.finding_rm %}Yes
                            {% else %}NO
                            {% endif %}</h4>


                        </div>

                        {% if request.session.role == 'admin' or request.session.username == comment.user.username %}
                            <form class="delete-form" method="POST"
                                  action="{% url "nova:delete-comment" property.id comment.id %}">
                                {% csrf_token %}
                                <input type="submit" class="delete-btn"
                                       value="Delete">
                            </form>
{#                            <button class="delete-btn" data-comment-id="{{ comment.id }}" data-ajax-url="{% url "nova:delete-comment" %}">Delete</button>#}



                                <button class="edit-btn">Edit</button>
                            </a>
                            {#'<int:property_id>/comments/<int:comment_id>/edit'#}
                        {% endif %}

                        <hr>



                    {% endfor %}
                </div>


            </div>

        </div>

{#        <div id="commentsSection">#}
{#            <!-- Existing comments will be here -->#}
{#        </div>#}



        {% if request.session.username %}
            <h3>Comment Poster: {{ request.session.username }}</h3>
            <form id="comment-form">
                <label>Rating: </label>
                <select name="add-rating" id="rating" required>
                    <option value=5> 5</option>
                    <option value=4> 4</option>
                    <option value=3> 3</option>
                    <option value=2> 2</option>
                    <option value=1> 1</option>
                </select> <br>
                <label>Is this property friendly to international student?</label>
                <select name="add-international-friendly" id="add-international-friendly" required>
                    <option value=True> Yes</option>
                    <option value=False> No</option>

                </select> <br>
                <label>Currently finding roommates in this building?</label>
                <select name="add-finding-rm" id="add-finding-rm" required>
                    <option value=True> Yes</option>
                    <option value=False> No</option>

                </select> <br>


                <textarea rows="8" cols="50" name="comment-text" placeholder="Write your comment..."></textarea> <br>

                <input type="hidden" id="property-id" name="property-id" value="{{ property.id }}">
                <input type="hidden" id="comment-poster" name="comment-poster" value="{{ request.session.username }}">
                <input type="submit" id="post-comment-input" value="Post Comment" data-property-id="{{ property.id }}"
                       data-ajax-url="{% url "nova:post-comment" %}">

                {% csrf_token %}
            </form>

        {% else %}
            <h2>You must log in to post a review!</h2>

        {% endif %}


    </div>

    {#    </div>#}
{% endblock %}

templates/nova/property/home-logged-in.html
{% extends "nova/base.html" %}
{% block page-title %} Home (Logged In) {% endblock %}
{% load static %}
{% load humanize %}

{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static "css/home-logged-in.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/list.css" %}">

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="welcome-section"><h1 id="welcome-message">Welcome Back, {{ request.session.username }}</h1>

    </div>

    <div class="lists-wrapper">
        <!--     First part will be the home you posted   -->
        <div id="properties-posted">
            <h2 class="home-post-title">The Home You Posted</h2>


            {% for property in properties %}

                {#                <h1>{{ property.house_name}}</h1>#}
                {% if property.poster == request.session.username %}
                    <div class="property">
                        <div class="house-image-section">

                            <div class="edit-delete-bar">

                                <a class="edit-link" href="{% url "nova:edit-property-page" property.id %}">
                                    <button class="edit-btn">Edit</button>
                                </a>
                                <form class="delete-form" method="POST"
                                  action="{% url "nova:delete-property" property.id %}">
                                {% csrf_token %}
                                <input type="submit" class="delete-btn"
                                       onclick="return confirm('Are you sure you want to delete this property?');"
                                       value="Delete">
                            </form>

                            </div>

                            <!--the pictures of the houses are from a website for free, public accessible photos https://unsplash.com/s/photos/house-->
                            <img data-description="{{ property.finding_rm }} people are finding a roommate in this property"
                                 class="building-img"
                                 src="{{ property.photo.url }}"
                                         alt="building"/>


                            <a class="view-more-link" href="{% url "nova:property-detail" property.id %}">
                                <button class="view-more-btn">View More</button>
                            </a>





                        </div>


                        <div class="basic-info">

                            <h3 class="house-title"> {{ property.house_name }}</h3>

                            <p class="address"> {{ property.address }}</p>
                            <hr>

                            <p>{{ property.rent_cost }}/month</p>
                            <hr>
                            <p>{{ property.bedrooms_count }} Beds, {{ property.bathrooms_count }}
                                Baths, {{ property.size }} Sq
                                Ft</p>
                            <hr>
                            <p class="date">Posted date: {{ property.date_posted|naturaltime }}</p>
                            <hr>
                             {% if property.is_verified %}
                            <p class="verify"><img src={% static "img/badge_check_icon.svg" %} class="badge"
                                                   alt="badge"/> Verified  </p>
                        {% else %}
                            <p class="verify"><img src={% static "img/badge_no_check_icon.svg" %} class="badge"
                                                   alt="badge"/> Not Verified  </p>
                        {% endif %}

                       |

                            <h4 class="availability">
                                {% if property.availability %}
                                Open
                            {% else %}
                                Full
                            {% endif %} </h4>
                        </div>
                    </div>

                {% endif %}

            {% endfor %}


        </div>
        <!--     Second part will be the home you put into the wish list   -->
{#        <div id="properties-wished">#}
{##}
{#            <h2 class="wish-list-title">Your Wish List</h2>#}
{##}
{#            <!--            Each block contain a property-->#}
{#            {% for property in properties %}#}
{#                {% if property.wished == request.session.username %}#}
{#                    <div class="property">#}
{#                        <div class="house-image-section">#}
{#                            <!--the pictures of the houses are from a website for free, public accessible photos https://unsplash.com/s/photos/house-->#}
{#                            <img data-description="{{ property.finding_rm }} people are finding a roommate in this property"#}
{#                                 class="building-img"#}
{#                                 src="{{ property.photo.url }}"#}
{#                                         alt="building"/>#}
{##}
{##}
{#                            <a class="view-more-link" href="{% url "nova:property-detail" property.id %}">#}
{#                                <button class="view-more-btn">View More</button>#}
{#                            </a>#}
{##}
{#                        </div>#}
{#                        <div class="basic-info">#}
{##}
{#                            <h3 class="house-title"> {{ property.house_name }}</h3>#}
{##}
{#                            <p class="address"> {{ property.address }}</p>#}
{#                            <hr>#}
{##}
{#                            <p>{{ property.rent_cost }}/month</p>#}
{#                            <hr>#}
{#                            <p>{{ property.bedrooms_count }} Beds, {{ property.bathrooms_count }}#}
{#                                Baths, {{ property.size }} Sq#}
{#                                Ft</p>#}
{#                            <hr>#}
{#                            <p class="date">{{ property.date_posted }}</p>#}
{#                            <hr>#}
{#                            <p class="verify"><img src={% static "img/badge_check_icon.svg" %} class="badge"#}
{#                                                   alt="badge"/> {{ property.is_verified }} | </p>#}
{#                            <p class="rating"><img src={% static "img/star-solid.svg" %} class="star"#}
{#                                                   alt="star"/> {{ property.rating }}</p> |#}
{#                            <h4 class="availability">{% if property.availability %}#}
{#                                Open#}
{#                            {% else %}#}
{#                                Full#}
{#                            {% endif %} </h4>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                {% endif %}#}
{##}
{##}
{#            {% endfor %}#}
{##}
{#        </div>#}

     <div id="properties-wished">
     {% include "actions/action/feed.html" %}
     </div>

{% endblock %}
{#{% block sidebar %}#}
{#   #}
{#{% endblock %}#}