djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path("/", include('nova.urls')),
    path("admin/", admin.site.urls),
    # The web page start from the properties/
    path('properties/', include('nova.urls', namespace="properties")),
    path('users/', include('users.urls', namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

nova/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "nova"
urlpatterns = [
    # properties views
    # Home page for logged-in user -> dashboard, not logged in user -> ad page
    path('', views.home_page, name="home-page"),
    path('about', views.about, name="about"),
    # Item list page
    path('properties-list', views.properties_list, name="properties-list"),


    # Register (not yet implement), only has interface

    path('search-result', views.search_result, name="search-result"),

    # CRUD properties
    path('post-property-page', views.post_property_page, name="post-property-page"),
    path('<int:property_id>/delete', views.delete_property, name='delete-property'),
    path('<int:property_id>/edit', views.edit_property_page, name="edit-property-page"),
    path('<int:property_id>', views.property_detail, name="property-detail"),
    # Comment CRUD
    path('comments/post', views.post_comment, name="post-comment"),
    path('<int:property_id>/comments/<int:comment_id>/delete', views.delete_comment, name="delete-comment"),
    # path('comments/delete', views.delete_comment, name='delete-comment'),
    path('<int:property_id>/comments/<int:comment_id>/edit', views.edit_comment, name="edit-comment")
    # path('<int:property_id>/comments', views.comments, name="comments"),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
app_name = "users"
urlpatterns = [
    # properties views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('profile/<str:username>/edit', views.edit_profile, name='edit-profile'),
    # Log in, Log out
    path('log-in', views.log_in_page, name="log-in-page"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),


]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nova/views.py
from django.contrib.auth.models import User
from django.db.models import Avg
from django.db.models.functions import Coalesce
from django.db.models import Avg, Value, FloatField
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect

from actions.models import Action
from .models import regular_user, admin_user, Property, Comments
from datetime import datetime
from django.contrib import messages
from django.utils.timesince import timesince


# Home page if log in: user dashboard, if not: ad welcome page
def home_page(request):
    if not request.session.get('username', False):
        return render(request, "nova/property/home.html")
    else:
        properties = Property.objects.all()
        user = User.objects.get(username=request.session.get('username'))
        own_actions = Action.objects.filter(user=user)

        user_properties = Property.objects.filter(user=user)

        related_actions = Action.objects.filter(target_id=user.id, verb="changed the role of")

        for property in user_properties:
            actions_for_property = Action.objects.filter(target_id=property.id)
            related_actions = related_actions | actions_for_property

        combined_actions = own_actions | related_actions
        return_actions = combined_actions.order_by('-created')[:15]


        return render(request, "nova/property/home-logged-in.html", {"properties": properties, "actions": return_actions})


def properties_list(request):
    sort_by = request.GET.get('sort', 'availability')  # default sort is by 'date_posted'

    # Use Coalesce to set the default average rating to 0 (If no ratings)
    properties = Property.objects.annotate(
        average_rating=Coalesce(Avg('comments__rating'), Value(0), output_field=FloatField())
    )

    if sort_by == 'house_name':
        # properties = Property.objects.all().order_by('house_name')
        properties = properties.order_by('house_name')
    elif sort_by == 'rent_cost':
        # properties = Property.objects.all().order_by('rent_cost')
        properties = properties.order_by('rent_cost')
    else:
        # properties = Property.objects.all().order_by('-availability')  # '-' indicates descending order
        properties = properties.order_by('-availability')  # '-' indicates descending order
    return render(request, "nova/property/list.html", {"properties": properties})


def property_detail(request, property_id):
    properties = Property.objects.annotate(
        average_rating=Coalesce(Avg('comments__rating'), Value(0), output_field=FloatField())
    )
    property = get_object_or_404(Property, id=property_id)
    comments = property.comments.all()
    comments = comments.order_by('-date_posted')
    # Calculate the average rating if there are reviews
    average_rating = comments.aggregate(Avg('rating'))['rating__avg']
    if average_rating is not None:
        average_rating = round(average_rating, 1)

    for property in properties:
        if property.id == property_id:
            # comments = Comments.objects.get(property)
            break

    return render(request,
                  "nova/property/detail.html",
                  {"property": property, "comments": comments, "average_rating": average_rating})


# Log in for regular user or admin user, determine which kind of the user is logged in


# Post a property (only for who is logged in)
def post_property_page(request):
    if not request.session.get('username', False):
        return redirect('users:log-in-page')
    if request.method == 'POST':
        # process the form
        # id
        house_name = request.POST.get('add-house-name')
        address = request.POST.get('add-address')
        availability = request.POST.get('add-availability')
        bathrooms_count = request.POST.get('add-bathrooms-count')
        bedrooms_count = request.POST.get('add-bedrooms-count')
        city = request.POST.get('add-city')
        date_posted = datetime.now()
        description = request.POST.get('add-description')
        finding_rm = False
        floor = request.POST.get('add-floor')
        initial_fee = request.POST.get('add-initial-fee')
        is_verified = False
        poster = request.POST.get('add-poster')
        # rating = 0.0
        rent_cost = request.POST.get('add-rent-cost')
        size = request.POST.get('add-size')
        unit = request.POST.get('add-unit')
        wished = "admin"
        zip_code = request.POST.get('add-zip-code')
        photo = request.FILES.get('add-photo')
        print(photo)
        np = Property(

            house_name=house_name,
            address=address,
            availability=availability,
            bathrooms_count=bathrooms_count,
            bedrooms_count=bedrooms_count,
            city=city,
            date_posted=date_posted,
            description=description,
            finding_rm=finding_rm,
            floor=floor,
            initial_fee=initial_fee,
            is_verified=is_verified,
            poster=poster,
            # rating=rating,
            rent_cost=rent_cost,
            size=size,
            unit=unit,
            # url=url,
            # wished=wished,
            zip_code=zip_code,
            photo=photo,
            user=User.objects.get(username=request.session.get("username"))

        )
        # Save to database
        np.save()

        action = Action(
            user=User.objects.get(username=request.session.get("username")),
            verb="posted a new house",
            target=np
        )
        action.save()

        # Message for indicating the status
        messages.add_message(request, messages.SUCCESS, "You successfully posted a new property: %s" % np.house_name)
        print(house_name, "has been posted")

        return redirect("nova:property-detail", np.id)
    else:
        return render(request, "nova/property/post.html")


# def user_home(request):
#     return render(request, "nova/property/home-logged-in.html", {"properties": properties})


def search_result(request):
    return render(request, "nova/property/search-result.html")


# Delete property URL is only accessible for admin user, regular user can't access only be redirected to the list
# page, and logged-in user will be navigated to the login page
def delete_property(request, property_id):
    property_to_delete = Property.objects.get(id=property_id)
    property_title = property_to_delete.house_name
    print(request.session.get("username"))
    print(property_to_delete.user.username)
    if not request.session.get('username', False):
        print("Please log in")
        return redirect('users:log-in-page')
    elif not request.session['role'] == 'admin' and request.session.get("username") != property_to_delete.user.username:
        print("You don't have permission, not admin")
        return redirect('nova:properties-list')
    elif request.session.get("username") != property_to_delete.user.username:
        print("You don't have permission to delete others' posts")
    else:
        action = Action(
            user=User.objects.get(username=request.session.get("username")),
            verb="deleted the house",
            target=property_to_delete,
            deleted_house_name=property_to_delete.house_name
        )
        action.save()

        # Delete the property
        property_to_delete.delete()

        print("Property id", property_id, "has been deleted")
        messages.add_message(request, messages.WARNING, "You deleted a property: %s" % property_title)

        # TODO:Delete operation
        return redirect('nova:properties-list')


def about(request):
    return render(request, "nova/about.html")


# Only logged in user can edit the property, clicking the corresponded property in the home page will leads to the edit page
def edit_property_page(request, property_id):
    if not request.session.get('username', False):
        return redirect('users:log-in-page')
    if request.method == 'POST':
        properties = Property.objects.all()
        for property in properties:
            if property.id == property_id:
                break

        if not request.session.get('username', False):
            return redirect('users:log-in-page')
        if request.method == 'POST':
            # process the form
            # id
            house_name = request.POST.get('edit-house-name')
            if property.house_name != house_name:
                action = Action(
                    user=User.objects.get(username=request.session.get("username")),
                    verb="edited the house title",
                    target=property
                )
                action.save()
            property.house_name = house_name
            address = request.POST.get('edit-address')
            property.address = address
            availability = request.POST.get('edit-availability')
            property.availability = availability
            bathrooms_count = request.POST.get('edit-bathrooms-count')
            property.bathrooms_count = bathrooms_count
            bedrooms_count = request.POST.get('edit-bedrooms-count')
            property.bedrooms_count = bedrooms_count
            city = request.POST.get('edit-city')
            property.city = city
            # date_posted = datetime.now()
            # property.date_posted = datetime.now()
            description = request.POST.get('edit-description')
            if property.description != description:
                action = Action(
                    user=User.objects.get(username=request.session.get("username")),
                    verb="edited the house description",
                    target=property
                )
                action.save()
            property.description = description
            # finding_rm = False

templates/nova/about.html
{%  extends "nova/base.html" %}
{% block page-title %} Detail {% endblock %}
{% load static %}


{% block content %}


    <h1>Overall purpose and intended audience</h1>
    <h4>An app can help international students rent homes and find roommates in Northern Virginia. It is difficult for international students to rent an apartment in the USA since most require a good credit score and social security number. The intended audience will be international students trying to rent a home or find roommates in Northern Virginia. This platform can help them find an apartment willing to have international students. To support truth and trust in an era of dis/misinformation, a verification and rating system is designed based on the feedback from tenants who lived there. A "Verified" badge will be next to content confirmed as "International students friendly and safe." The users can also interact and communicate with each other to discuss housing or finding roommates. In this way, students can avoid finding suspicious or unqualified apartments. The objective is to link international students with legitimate apartments that welcome them and prevent scams. The key "item" of the web app will be the housing profiles.</h4>



{% endblock %}

templates/nova/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NoVA Renting | {% block page-title %}{% endblock %} </title>
    <link rel="stylesheet" type="text/css" href={% static "css/responsive.css" %}>

    <script src={% static "js/jquery-3.7.1.min.js" %}></script>
    <script src={% static "js/script.js" %}></script>
    <meta name="viewport" content="width=device-width">
</head>
<body>

<div id="header">


    <div id="logo-box">
        <!--        The logo is made from a free logo making website https://www.canva.com/create/logos/-->
{#        {% if  request.session.username%}#}
{#            <a href="{% url 'nova:user-home' %}"><img id="logo" alt="logo" src={% static "img/logo.png"%}/></a>#}
{#        {% else %}#}
{#             <a href="{% url 'nova:home-page' %}"><img id="logo" alt="logo" src={% static "img/logo.png"%}/></a>#}
{#        {% endif %}#}

        <div id="title-box">
            <h1>NoVA Renting</h1>
            <h2>A site for helping international student</h2>

        </div>


        <!-- Search Bar -->


    </div>


    <div class="search-bar-div">
        <form action="{% url "nova:search-result" %}" class="search-box" method="get">

            <input type="text" name="search-property" class="search-bar" placeholder="Enter a property name"/>

            <!--             Search bottom -->
            <button type="submit" name="submit" value="Go" class="search-button">
                <img class="search-icon" src={% static "img/search-icon.svg"%} alt="Search" width="24" height="24"/>
            </button>

        </form>
    </div>





    <!--    nav bar -->
    <div id="primary-nav">
{#    {% if request.session.username %}#}
{#        <a href="{% url "nova:user-home" %}">Home</a>#}
{#    {% else %}#}
        <a href="{% url "nova:home-page" %}" class="nav-link-home">Home</a>
{#    {% endif %}#}



        <a href="{% url "nova:properties-list" %}" class="nav-link-list">List</a>
{#    {% if request.session.username %}#}
        <a href="{% url "nova:post-property-page" %}" class="nav-link-post">Post</a>
{#    {% else %}#}
{#        <a href="{% url "nova:log-in-page" %}">Post</a>#}
{#    {% endif %}#}

        <a href="{% url "nova:about" %}" class="nav-link-about">About</a>
        {% if request.session.username %}
            <a href="{% url 'users:profile' request.session.username%}">(<strong>{{ request.session.username }}</strong>) Profile </a>
               <a href="{% url 'users:logout'%}"> Log Out </a>

        {% else %}
         <a href="{% url "users:log-in-page" %}"  class="nav-link-login">Log In</a>
        {% endif %}
    </div>


</div> <!-- #header -->




<div id="content">
{% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

{% block content %}{% endblock %}


</div>


<div id="footer">



    <p id="footer-nav">
{#        {% if  request.session.username%}#}
{#            <a href="{% url 'nova:user-home' %}">Home</a>#}
{#        {% else %}#}
             <a href="{% url 'nova:home-page' %}">Home</a>
{#        {% endif %}#}
        | <a href="{% url 'nova:properties-list' %}">List</a> | <a  href="{% url "nova:about" %}">About</a> |
        <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2023 RICHVA Inc.</p>

</div>


</body>
</html>