djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path("/", include('nova.urls')),
    path("admin/", admin.site.urls),
    # The web page start from the properties/
    path('properties/', include('nova.urls', namespace="properties")),
    path('users/', include('users.urls', namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

nova/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "nova"
urlpatterns = [
    # properties views
    # Home page for logged-in user -> dashboard, not logged in user -> ad page
    path('', views.home_page, name="home-page"),
    path('about', views.about, name="about"),
    # Item list page
    path('properties-list', views.properties_list, name="properties-list"),


    # Register (not yet implement), only has interface

    path('search-result', views.search_result, name="search-result"),

    # CRUD properties
    path('post-property-page', views.post_property_page, name="post-property-page"),
    path('<int:property_id>/delete', views.delete_property, name='delete-property'),
    path('<int:property_id>/edit', views.edit_property_page, name="edit-property-page"),
    path('<int:property_id>', views.property_detail, name="property-detail"),
    # Comment CRUD
    path('comments/post', views.post_comment, name="post-comment"),
    path('<int:property_id>/comments/<int:comment_id>/delete', views.delete_comment, name="delete-comment"),
    # path('comments/delete', views.delete_comment, name='delete-comment'),
    path('<int:property_id>/comments/<int:comment_id>/edit', views.edit_comment, name="edit-comment")
    # path('<int:property_id>/comments', views.comments, name="comments"),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
app_name = "users"
urlpatterns = [
    # properties views
    path('register', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('profile/<str:username>/edit', views.edit_profile, name='edit-profile'),
    # Log in, Log out
    path('log-in', views.log_in_page, name="log-in-page"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),


]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


# Create your models here.
class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="regular", max_length=50)
    subscription = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('users:profile', args=[self.username])


@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from actions.models import Action
from nova.models import admin_user, regular_user


def profile(request, username):
    user1 = get_object_or_404(User, username=username)
    actions = Action.objects.filter(user=user1).order_by('-created')[:15]
    # actions = Action.objects.all().order_by('-created')[:15]
    return render(request, "users/user/profile.html", {"user": user1, "actions": actions})


def edit_profile(request, username):
    if not request.session.get('username', False):
        return redirect('users:log-in-page')

    else:
        user1 = get_object_or_404(User, username=username)

    if request.session.get('username') == username or request.session.get('role') == 'admin':

        if request.method == 'POST':

            # id
            # username = request.POST.get('edit-username')
            # user1.username = username
            email = request.POST.get('edit-email')
            user1.email = email
            first_name = request.POST.get('edit-first-name')
            user1.first_name = first_name
            last_name = request.POST.get('edit-last-name')
            user1.last_name = last_name
            subscription = request.POST.get('edit-subscription')
            user1.details.subscription = subscription
            # print(user1.details.role)

            if request.session.get('username') == username:
                new_password = request.POST.get('edit-password')
                # user1.password = new_password
                user1.set_password(new_password)

            if request.session.get('role') == 'admin':
                role = request.POST.get('edit-role')

                # print(role)
                # print(user1.details.role)
                if user1.details.role != role:
                    user1.details.role = role
                    action = Action(
                        user=User.objects.get(username=request.session.get("username")),
                        verb="changed the role of",
                        target=user1
                    )
                    action.save()


            user1.save()
            print(user1.username, "'s profile has been edited")
            return redirect("users:profile", user1.username)
        else:

            return render(request, "users/user/edit-profile.html", {"user": user1})
    else:


        actions = Action.objects.filter(user=user1).order_by('-created')[:15]
        # actions = Action.objects.all().order_by('-created')[:15]
        return render(request, "users/user/profile.html", {"user": user1, "actions": actions})

















# Create your views here.
def register(request):
    if request.method == 'POST':
        username = request.POST.get('register-username')
        email = request.POST.get('register-email')
        password = request.POST.get('register-password')
        if User.objects.filter(username=username).exists() or User.objects.filter(email=email):
            # messages.error(request, "Username '%s' is already taken. Please choose a different one." % username)
            return render(request, "users/user/register.html", {'error': 'Username or email already taken'})
        else:
            user = User.objects.create_user(username, email, password)
            messages.add_message(request, messages.SUCCESS,
                                 "You successfully registered with the username: %s" % user.username)
            user = authenticate(username=username, password=password)
            if user is not None:
                request.session['username'] = user.username
                request.session['role'] = user.details.role
                return redirect('nova:properties-list')
            return redirect('nova:properties-list')

    else:
        return render(request, "users/user/register.html")


def login(request):
    username = request.POST.get("username")
    pw = request.POST.get("pw")

    user = authenticate(username=username, password=pw)
    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        return redirect('nova:properties-list')
    else:
        context = {'error': 'Incorrect username or password.'}
        return render(request, "users/user/login.html", context)
        # messages.add_message(request, messages.SUCCESS,
        #                      "Invalid username or password.")

    # if (username == admin_user['username']) and (pw == admin_user['password']):
    #
    #
    #     return redirect('nova:properties-list')
    # elif (username == regular_user['username']) and (pw == regular_user['password']):
    #     request.session['username'] = username
    #     request.session['role'] = 'regular'
    #     return redirect('nova:properties-list')
    #
    # else:
    #     # messages.add_message(request, messages.WARNING, "Incorrect username or password.")
    #     # Incorrect username/password, do not redirect but render the login page with an error
    #     context = {'error': 'Incorrect username or password.'}
    #     return render(request, "users/user/login.html", context)

    # return redirect('nova:log-in-page')


def logout(request):
    del request.session['username']
    del request.session['role']
    return redirect('nova:home-page')


def log_in_page(request):
    return render(request, "users/user/login.html")

templates/users/user/edit-profile.html
{% extends "nova/base.html" %}
{% block page-title %} Profile for {{ user.username }} {% endblock %}
{% load static %}


{% block content %}

<link rel="stylesheet" type="text/css" href={% static "css/profile.css" %}>
    <h2 id="section-heading">Profile for {{ user.username }}</h2>

    <form action="{% url 'users:edit-profile' user.username %}" method="post">
        {% csrf_token %}
     <button type="submit">Save</button>




    <dl>
    <dt>Username</dt>
    <dd>{{ user.username }}</dd>
    <dt>*Email address</dt>
    <dd><label>
        <input type="email" id="edit-email" name="edit-email" value="{{ user.email }}" required/>
    </label></dd>
        <dt>First Name</dt>
    <dd><label>
        <input type="text" id="edit-first-name" name="edit-first-name" value="{{ user.first_name }}" />
    </label></dd>
        <dt>Last Name</dt>
    <dd><label>
        <input type="text" id="edit-last-name" name="edit-last-name" value="{{ user.last_name }}" />
    </label></dd>
        <dt>Email Subscription</dt>
    <dd><label>
        <input type="radio" id="edit-subscription" name="edit-subscription" value="True" {% if user.details.subscription %}checked{% endif %} />
        Subscribe to email news
    </label>
    <label>
        <input type="radio" id="edit-subscription" name="edit-subscription" value="False" {% if not user.details.subscription %}checked{% endif %} />
        Do not subscribe to email news
    </label></dd>
    {% if request.session.role == 'admin' %}

    <dt>Role</dt>
    <dd><label>
        <input type="radio" id="edit-role-regular" name="edit-role" value="regular" {% if user.details.role == 'regular' %}checked{% endif %} />
        User
    </label>
    <label>
        <input type="radio" id="edit-role-admin" name="edit-role" value="admin" {% if user.details.role == 'admin' %}checked{% endif %} />
        Admin
    </label></dd>
     {% endif %}

    {% if request.session.username == user.username  %}
    <dt>*Change Password</dt>
    <dd>
        <label for="edit-password">Type your Original Password or New Password</label>
        <input type="password" id="edit-password" name="edit-password"  required />
    </dd>

  {% endif %}

    </dl>
     </form>
{% endblock %}

templates/users/user/login.html
{% extends "nova/base.html" %}
{% block page-title %} Detail {% endblock %}
{% load static %}


{% block content %}
    <link rel="stylesheet" type="text/css" href={% static "css/login.css" %}>

    <div id="login-section">
        <form id="login-box" action="{% url "users:login" %}" method="POST">
            {% csrf_token %}
            <h2>Please Log In</h2>
            {% if error %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endif %}

            <label>
                <input type="text" name="username" placeholder="Username">
            </label>

            <label>
                <input type="password" name="pw" placeholder="Password">
            </label>
            <input type="submit" name="submit" value="Log in"> or <a href="{% url "users:register" %}">Register</a>
        </form>
    </div>


{% endblock %}

templates/users/user/profile.html
{% extends "nova/base.html" %}
{% block page-title %} Profile for {{ user.username }} {% endblock %}
{% load static %}


{% block content %}
    <link rel="stylesheet" type="text/css" href={% static "css/profile.css" %}>
    <h2 id="section-heading">Profile for {{ user.username }}</h2>
    {% if request.session.username == user.username or request.session.role == 'admin'%}

    <button class="btn" onclick="location.href='{% url 'users:edit-profile' user.username %}';">Edit Profile</button>
 {% endif %}
    <dl>
    <dt>Username</dt>
    <dd>{{ user.username }}</dd>
    <dt>Email address</dt>
    <dd>{{ user.email }}</dd>
        <dt>First Name</dt>
    <dd>{{ user.first_name }}</dd>
        <dt>Last Name</dt>
    <dd>{{ user.last_name }}</dd>
        <dt>Email Subscription</dt>
    <dd>{% if user.details.subscription %} Subscribed to the email news{% else %} Not subscribing to the email news{% endif %}</dd>
    <dt>Role</dt>
    <dd>{{ user.details.role }}</dd>

    </dl>




    {#    </div>#}
    <center>{% include "actions/action/feed.html" %}</center>
{% endblock %}

templates/users/user/register.html
{%  extends "nova/base.html" %}
{% block page-title %} Detail {% endblock %}
{% load static %}


{% block content %}
<link rel="stylesheet" type="text/css" href={% static "css/login.css" %}>

   <div id="login-section">
       <form id="login-box" action="{% url "users:register" %}" method="POST">
        {% csrf_token %}
           <h2>Register</h2>
           {% if error %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endif %}
        <label>
            Name:
            <input type="text" name="register-username" placeholder="Username" required>
        </label>
           <label>Email Address:
            <input type="email" name="register-email" placeholder="Email" required>
        </label>
        <label>
            Password:
            <input type="password" name="register-password" placeholder="Password" required>
        </label>
        <input type="submit" name="submit" value="Register">
    </form>
   </div>


{% endblock %}